pub const SIMULATION_HZ: u32 = 100;
pub const SIMULATION_DURATION: f32 = 1.0 / SIMULATION_HZ as f32;

pub const SW_FRAME_RATE_HZ: f32 = 60.0;
pub const SW_FRAME_RATE_DURATION: f32 = 1.0 / SW_FRAME_RATE_HZ;